# This is the Quartus file list for 'DSPB_MMSE_dut_feature_extraction_a_posteriori_SNR_x'

set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_safe_path.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_safe_path.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_safe_path.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_safe_path.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_feature_extraction_a_posteriori_SNR_x.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_feature_extraction_a_posteriori_SNR_x.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_feature_extraction_a_posteriori_SNR_x.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_feature_extraction_a_posteriori_SNR_x.vhd
source ./rtl/DSPB_MMSE/floatComponent_DSPB_MMSE_dut_feature_extraction_a_posteriori_SNR_castBlock_typeUA0Zcdo6u2oct30u.add.tcl
source ./rtl/DSPB_MMSE/floatComponent_DSPB_MMSE_dut_feature_extraction_a_posteriori_SNR_castBlock_typeUA0Zcdo6u2oct30u.add.tcl
source ./rtl/DSPB_MMSE/floatComponent_DSPB_MMSE_dut_feature_extraction_a_posteriori_SNR_divideBlock_typA0Z4ad20454ck5u.add.tcl
