# This is the Quartus file list for 'DSPB_MMSE_dut_feature_extraction_a_priori_SNR_x'

set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_safe_path.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_safe_path.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_safe_path.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_safe_path.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_feature_extraction_a_priori_SNR_x.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_feature_extraction_a_priori_SNR_x.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_feature_extraction_a_priori_SNR_x.vhd
set_global_assignment -name VHDL_FILE ./rtl/DSPB_MMSE/DSPB_MMSE_dut_feature_extraction_a_priori_SNR_x.vhd
source ./rtl/DSPB_MMSE/floatComponent_DSPB_MMSE_dut_feature_extraction_a_priori_SNR_addBlock_typeSFloatA0Z0454c226155y.add.tcl
source ./rtl/DSPB_MMSE/floatComponent_DSPB_MMSE_dut_feature_extraction_a_priori_SNR_castBlock_typeSFloaA0Zcdo6u2oct30u.add.tcl
source ./rtl/DSPB_MMSE/floatComponent_DSPB_MMSE_dut_feature_extraction_a_priori_SNR_divideBlock_typeSFlA0Z4ad20454ck5u.add.tcl
source ./rtl/DSPB_MMSE/floatComponent_DSPB_MMSE_dut_feature_extraction_a_priori_SNR_maxBlock_typeSFloatA0Zocpq6c0owfzo.add.tcl
source ./rtl/DSPB_MMSE/floatComponent_DSPB_MMSE_dut_feature_extraction_a_priori_SNR_multBlock_typeSFloaA0Z4ad20454ck5u.add.tcl
source ./rtl/DSPB_MMSE/floatComponent_DSPB_MMSE_dut_feature_extraction_a_priori_SNR_multBlock_typeSFloaA1Z4ad20454ck5u.add.tcl
source ./rtl/DSPB_MMSE/floatComponent_DSPB_MMSE_dut_feature_extraction_a_priori_SNR_multBlock_typeSFloaA1Z4ad20454ck5u.add.tcl
source ./rtl/DSPB_MMSE/floatComponent_DSPB_MMSE_dut_feature_extraction_a_priori_SNR_subBlock_typeSFloatA0Zad20454c2abw.add.tcl
