// This is the memory map header file for 'DSPB_MMSE'
// Generated by High Level Design Compiler for Intel(R) FPGAs Version 18.1 (Release Build #625) on Mon Aug 16 17:44:01 2021

// This file contains the address of each register in the design, with the block name, 
// read/write mode, and description in the block parameters as comments for each.

// Each section denotes one ModelIP/ModelBus block and is laid out as follows:
// <block name> : <description from block>
// <REGISTER_NAME>_BIT_WIDTH <bit width from block>
// <REGISTER_NAME>_FRAC_WIDTH <frac width from block>
// <REGISTER_NAME>_PRIVATE_SPACE <is the private register space box checked?>
// Then, for each addressable word of the block:
// <REGISTER_NAME>_LSB <LSB of word>
// <REGISTER_NAME>_MSB <MSB of word>
// <REGISTER_NAME>_WIDTH <width of word>
// <REGISTER_NAME> <word address in hex format> <read/write mode>

#define AVALON_BUS_WIDTH 16
#define AVALON_ADDRESS_WIDTH 10
// DSPB_MMSE/dut/Output_IF/RegOut : Estimated_SNR_Db
#define DSPB_MMSE_DUT_OUTPUT_IF_REGOUT_BIT_WIDTH 16
#define DSPB_MMSE_DUT_OUTPUT_IF_REGOUT_FRAC_WIDTH 8
#define DSPB_MMSE_DUT_OUTPUT_IF_REGOUT_PRIVATE_SPACE false
#define DSPB_MMSE_DUT_OUTPUT_IF_REGOUT_LSB 0
#define DSPB_MMSE_DUT_OUTPUT_IF_REGOUT_MSB 15
#define DSPB_MMSE_DUT_OUTPUT_IF_REGOUT_WIDTH 16
#define DSPB_MMSE_DUT_OUTPUT_IF_REGOUT 0x322 // Read 

// DSPB_MMSE/dut/Output_IF/output_fifo : output fifo
#define DSPB_MMSE_DUT_OUTPUT_IF_OUTPUT_FIFO_BIT_WIDTH 16
#define DSPB_MMSE_DUT_OUTPUT_IF_OUTPUT_FIFO_FRAC_WIDTH 11
#define DSPB_MMSE_DUT_OUTPUT_IF_OUTPUT_FIFO_PRIVATE_SPACE false
#define DSPB_MMSE_DUT_OUTPUT_IF_OUTPUT_FIFO_LSB 0
#define DSPB_MMSE_DUT_OUTPUT_IF_OUTPUT_FIFO_MSB 15
#define DSPB_MMSE_DUT_OUTPUT_IF_OUTPUT_FIFO_WIDTH 16
#define DSPB_MMSE_DUT_OUTPUT_IF_OUTPUT_FIFO_STARTADDR 0x191 // Read/Write 
#define DSPB_MMSE_DUT_OUTPUT_IF_OUTPUT_FIFO_LENGTH 401 

// DSPB_MMSE/dut/input_IF/input_fifo : input fifo
#define DSPB_MMSE_DUT_INPUT_IF_INPUT_FIFO_BIT_WIDTH 16
#define DSPB_MMSE_DUT_INPUT_IF_INPUT_FIFO_FRAC_WIDTH 14
#define DSPB_MMSE_DUT_INPUT_IF_INPUT_FIFO_PRIVATE_SPACE false
#define DSPB_MMSE_DUT_INPUT_IF_INPUT_FIFO_LSB 0
#define DSPB_MMSE_DUT_INPUT_IF_INPUT_FIFO_MSB 15
#define DSPB_MMSE_DUT_INPUT_IF_INPUT_FIFO_WIDTH 16
#define DSPB_MMSE_DUT_INPUT_IF_INPUT_FIFO_STARTADDR 0x0 // Read/Write 
#define DSPB_MMSE_DUT_INPUT_IF_INPUT_FIFO_LENGTH 401 

