# This is the hw.tcl file for 'dsp_vad_VAD'
# Generated by High Level Design Compiler for Intel(R) FPGAs 

package require -exact qsys 14.1

# module dsp_vad_VAD
set_module_property NAME dsp_vad_VAD
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Altera DSP Builder Advanced"
set_module_property DISPLAY_NAME dsp_vad_VAD
set_module_property EDITABLE false

# filesets
add_fileset DSPBA_QUARTUS_SYNTH QUARTUS_SYNTH quartus_synth_callback
set_fileset_property DSPBA_QUARTUS_SYNTH TOP_LEVEL dsp_vad_VAD

proc quartus_synth_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "dsp_vad_VAD_safe_path_flat.vhd" VHDL PATH "dsp_vad_VAD_safe_path_flat.vhd"
	add_fileset_file "dsp_vad_VAD.vhd" VHDL PATH "dsp_vad_VAD.vhd"
	add_fileset_file "busSlaveFabric_dsp_vad_VAD_2uuidx4a06e636r6g6u0qu5xajz.vhd" VHDL PATH "busSlaveFabric_dsp_vad_VAD_2uuidx4a06e636r6g6u0qu5xajz.vhd"
}
add_fileset DSPBA_SIM_VERILOG SIM_VERILOG sim_verilog_callback
set_fileset_property DSPBA_SIM_VERILOG TOP_LEVEL dsp_vad_VAD

proc sim_verilog_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "dsp_vad_VAD_safe_path_flat.vhd" VHDL PATH "dsp_vad_VAD_safe_path_flat.vhd"
	add_fileset_file "dsp_vad_VAD.vhd" VHDL PATH "dsp_vad_VAD.vhd"
	add_fileset_file "busSlaveFabric_dsp_vad_VAD_2uuidx4a06e636r6g6u0qu5xajz.vhd" VHDL PATH "busSlaveFabric_dsp_vad_VAD_2uuidx4a06e636r6g6u0qu5xajz.vhd"
}
add_fileset DSPBA_SIM_VHDL SIM_VHDL sim_vhdl_callback
set_fileset_property DSPBA_SIM_VHDL TOP_LEVEL dsp_vad_VAD

proc sim_vhdl_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "dsp_vad_VAD_safe_path_flat.vhd" VHDL PATH "dsp_vad_VAD_safe_path_flat.vhd"
	add_fileset_file "dsp_vad_VAD.vhd" VHDL PATH "dsp_vad_VAD.vhd"
	add_fileset_file "busSlaveFabric_dsp_vad_VAD_2uuidx4a06e636r6g6u0qu5xajz.vhd" VHDL PATH "busSlaveFabric_dsp_vad_VAD_2uuidx4a06e636r6g6u0qu5xajz.vhd"
}

# interfaces
# Interface clock
add_interface clock clock end
set_interface_property clock ENABLED true
add_interface_port clock clk clk Input 1
add_interface_port clock areset reset Input 1

# Interface bus_reset
add_interface bus_reset reset end
set_interface_property bus_reset ENABLED true
set_interface_property bus_reset ASSOCIATED_CLOCK clock
add_interface_port bus_reset h_areset reset Input 1

# Interface bus
add_interface bus avalon slave
set_interface_property bus maximumPendingReadTransactions 1
set_interface_property bus setupTime 0
set_interface_property bus ASSOCIATED_CLOCK clock
set_interface_property bus ENABLED true
add_interface_port bus busIn_address address Input 3
add_interface_port bus busIn_read read Input 1
set_port_property busIn_read VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port bus busIn_write write Input 1
set_port_property busIn_write VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port bus busIn_writedata writedata Input 32
add_interface_port bus busOut_readdata readdata Output 32
add_interface_port bus busOut_readdatavalid readdatavalid Output 1
set_port_property busOut_readdatavalid VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port bus busOut_waitrequest waitrequest Output 1
set_port_property busOut_waitrequest VHDL_TYPE STD_LOGIC_VECTOR
