// This is the memory map header file for 'dsp_vad'
// Generated by High Level Design Compiler for Intel(R) FPGAs Version 18.1 (Release Build #646) on Sat Feb 01 20:40:56 2020

// This file contains the address of each register in the design, with the block name, 
// read/write mode, and description in the block parameters as comments for each.

// Each section denotes one ModelIP/ModelBus block and is laid out as follows:
// <block name> : <description from block>
// <REGISTER_NAME>_BIT_WIDTH <bit width from block>
// <REGISTER_NAME>_FRAC_WIDTH <frac width from block>
// <REGISTER_NAME>_PRIVATE_SPACE <is the private register space box checked?>
// Then, for each addressable word of the block:
// <REGISTER_NAME>_LSB <LSB of word>
// <REGISTER_NAME>_MSB <MSB of word>
// <REGISTER_NAME>_WIDTH <width of word>
// <REGISTER_NAME> <word address in hex format> <read/write mode>

#define AVALON_BUS_WIDTH 32
#define AVALON_ADDRESS_WIDTH 3
// dsp_vad/VAD/sys_mm_in/fft_out_pop : Description of what is stored in this field
#define DSP_VAD_VAD_SYS_MM_IN_FFT_OUT_POP_BIT_WIDTH 32
#define DSP_VAD_VAD_SYS_MM_IN_FFT_OUT_POP_FRAC_WIDTH 23
#define DSP_VAD_VAD_SYS_MM_IN_FFT_OUT_POP_PRIVATE_SPACE false
#define DSP_VAD_VAD_SYS_MM_IN_FFT_OUT_POP_LSB 0
#define DSP_VAD_VAD_SYS_MM_IN_FFT_OUT_POP_MSB 31
#define DSP_VAD_VAD_SYS_MM_IN_FFT_OUT_POP_WIDTH 32
#define DSP_VAD_VAD_SYS_MM_IN_FFT_OUT_POP 0x3 // Read/Write 

// dsp_vad/VAD/sys_mm_in/sample_data : Description of what is stored in this field
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_DATA_BIT_WIDTH 32
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_DATA_FRAC_WIDTH 23
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_DATA_PRIVATE_SPACE false
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_DATA_LSB 0
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_DATA_MSB 31
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_DATA_WIDTH 32
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_DATA 0x1 // Read/Write 

// dsp_vad/VAD/sys_mm_in/sample_in _valid : Description of what is stored in this field
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_IN_VALID_BIT_WIDTH 32
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_IN_VALID_FRAC_WIDTH 23
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_IN_VALID_PRIVATE_SPACE false
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_IN_VALID_LSB 0
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_IN_VALID_MSB 31
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_IN_VALID_WIDTH 32
#define DSP_VAD_VAD_SYS_MM_IN_SAMPLE_IN_VALID 0x0 // Read/Write 

