#pragma once
#pragma once
//FPGA_mgr

//IO_mgr
#define DEFAULT_FRAME_LENGTH 0.025f
#define	FPGA_INPUT_IF_FRACTIONAL_BITS 14
#define	FPGA_OUTPUT_IF_FRACTIONAL_BITS 10
#define FPGA_RBF_COMPAT_CHECK_VAL	1.23f
#define SF 16e3